version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: .
    command: bash -c "python django_project/manage.py migrate && (echo yes | python django_project/manage.py collectstatic) && python django_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_NAME=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env

    nginx:
      image: nginx
      depends_on:
        - server
      volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"