# Generated by Django 5.1.5 on 2025-01-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
